@startuml
!$batch=true

class Batch
'A batch of Produce of a crop.
{
Reference : text
'A reference for the batch.
}

!if %variable_exists("$transfer")
Transfer "0..1" -- "1" Batch : > from
Batch "1" -- "0..*" Transfer : < to
!endif

!if %variable_exists("$test")
Batch "1" -- "0..*" Test : < on
!endif

!if %variable_exists("$processing")
Batch "1" -- "0..*" Processing : < of
!endif

!if %variable_exists("$harvest")
Batch "1" -- "0..*" Harvest : < into
!endif

!if %variable_exists("$planting")
Batch "1" -- "0..*" Planting : < from
!endif

!if %variable_exists("$sale")
Batch "1" -- "0..*" Sale : < from
!endif

!if %variable_exists("$purchase")
Batch "1" -- "0..*" Purchase : < into
!endif

@enduml