@startuml
!$batch=true

class Batch
'A batch of Produce of a crop.
{
Reference : text
'A reference for the batch.
}

!if %variable_exists("$transfer")
note "{ Batches must be of same Produce }" as N1

Transfer "0..1" -- "1" Batch : > from
Batch "1" -- "0..*" Transfer : < to
(Transfer,Batch) .. N1
(Batch,Transfer) .. N1

!endif

!if %variable_exists("$test")
Batch "1" -- "0..*" Test : < on
!endif

!if %variable_exists("$processing")
Batch "1" -- "0..*" Processing : < delivers into
!endif

!if %variable_exists("$harvest")
Batch "1" -- "0..*" Harvest : < of
!endif

!if %variable_exists("$planting")
Batch "1" -- "0..*" Planting : < from
!endif

!if %variable_exists("$sale")
Batch "1" -- "0..*" Sale : < from
!endif

!if %variable_exists("$purchase")
Batch "1" -- "0..*" Purchase : < into
!endif

@enduml