!$crop=true

class Crop
'Plants harvested for some use
{
Species : text
'The species of the producing plants
Variety : text
'The variety (cultivar) of the producing crop
Part : text
'The part of the plant (e.g.grain, or straw)
}

!if %variable_exists("$batch")
Batch "0..2" -- "0..*" Crop : > of
!endif