!$harvest=true

class Harvest 
'Harvest of produce from a location.
{
	DateTime : datetime
	'Date and time of the Harvest.'
	Quantity : number
	'Quantity of material harvested in kilogrammes.'
}

!if %variable_exists("$location")
Harvest "0..*"  -- "1" Location : > at
!endif