!$location=true

abstract Location
'A location on the Earth's surface with some relation to crop production.

!if %variable_exists("$point")
Location <|-- Point
!endif

!if %variable_exists("$path")
Location <|-- Path
!endif

!if %variable_exists("$region")
Location <|-- Region
!endif
