!$material=true

abstract Material
'A kind of material consumed, or produced in a crop production system.

!if %variable_exists("$batch")
Material "1" -- "0..*" Batch : < of
!endif

!if %variable_exists("$produce")
Material <|-- Produce
!endif

!if %variable_exists("$substance")
Material <|-- Substance
!endif