!$obervation=true

abstract Observation
'An observation at a location related to crop production.'
{
	DateTime : datetime 
	'The date and time of the observation. '
}

!if %variable_exists("$location")
Observation "0..*" -- "1" Location : > at
!endif

