!$planting=true

class Planting 
'Planting/sowing of a crop.
{
	DateTime : datetime
	'Date and time of the planting/sowing.'
	Quantity : number
	'Quantity of material planted/sown in kilogrammes.'
	Broadcast : boolean
	'True if the planting was random, or the sowing was broadcast.
}