!$planting=true

class Planting 
'Planting/sowing of a crop.
{
	DateTime : datetime
	'Date and time of the planting/sowing.'
	Quantity : number
	'Quantity of material planted/sown in kilogrammes.'
}

!if %variable_exists("$location")
Planting "0..*"  -- "1" Location : > at
!endif