!$point=true

class Point 
'A point, with some relevance to crop production, in a rectangle representing an Equirectangular projection of the Earth's surface .
{
  Latitude : number
  'the latitude of the Point expressed in decimal degrees to a precision of no more than 7 decimal places
  Longitude : number
  'the longitude of the Point expressed in decimal degrees to a precision of no more than 7 decimal places
}
