!$unmapped = true

class UnmappedPoint
'An unmapped point having some relevance to crop production

class UnmappedPath
'An unmapped path on the Earth's surface with some relation to crop production.
{
	Length : number
	'Length of the unmapped path in metres.
}

class UnmappedRegion
'An unmapped region of the Earth's surface with some relation to crop production which may consist of any number of non-contiguous parts.
{
	Area : number
	'Area of the unmapped region in hectares.
}
