@startuml
hide circle
!include https://raw.github.com/Charles1625/crop-production-ontology/main/Model/batch.puml
!include https://raw.github.com/Charles1625/crop-production-ontology/main/Model/crop.puml
@enduml