@startuml
hide circle
abstract RegionReference <<dataType>>
'A reference for a region.
class UKFieldReference <<dataType>> 
'An example of a RegionReference
{
OSParcelID : text
FieldName : text
FieldNo : number
}
RegionReference <|-- UKFieldReference
@enduml