@startuml
hide circle
abstract Polygon { 
Area() : number
Intersection(polygon: Polygon) : Polygon
Contains(point : Point)  : boolean
}

class Region {
Reference : RegionReference
Area() : number
Intersection(region: Region) : Region
Contains(location : Location) : boolean
}

class IncludedPolygon

class ExcludedPolygon

Polygon <|-- IncludedPolygon

Polygon <|-- ExcludedPolygon

Region o-- "1..*" IncludedPolygon : > has

IncludedPolygon o-- "0..*" ExcludedPolygon : > has
@enduml