@startuml
hide circle
!$region=true
!include https://raw.github.com/Charles1625/crop-production-ontology/main/Model/datatypes.puml

class UKFieldReference <<dataType>> 
'An example of a RegionReference
{
OSParcelID : text
FieldName : text
FieldNo : number
}
RegionReference <|-- UKFieldReference
@enduml