@startuml
hide circle
!include https://raw.github.com/Charles1625/crop-production-ontology/main/Model/polygon.puml
!include https://raw.github.com/Charles1625/crop-production-ontology/main/Model/region.puml
!include https://raw.github.com/Charles1625/crop-production-ontology/main/Model/included-polygon.puml
!include https://raw.github.com/Charles1625/crop-production-ontology/main/Model/excluded-polygon.puml
@enduml