@startuml
hide circle

!include ../Model/location.puml
!include ../Model/transfer.puml
!include ../Model/test.puml
!include ../Model/processing.puml
!include ../Model/harvest.puml
!include ../Model/planting.puml
!include ../Model/crop.puml
!include ../Model/purchase.puml
!include ../Model/sale.puml
!include ../Model/batch.puml
@enduml